// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_Cfv7F4WDEQpCN5Sdk7L01ZpNSG0zv0',
    appId: '1:301675624288:web:2b667ac5bd561c3e025005',
    messagingSenderId: '301675624288',
    projectId: 'chatapp-8e5db',
    authDomain: 'chatapp-8e5db.firebaseapp.com',
    storageBucket: 'chatapp-8e5db.appspot.com',
    measurementId: 'G-2K07BWQWBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCygfk6hX7D9XjNFZZRrvdi-LwTSIBYzGA',
    appId: '1:301675624288:android:10fa110e47b395ef025005',
    messagingSenderId: '301675624288',
    projectId: 'chatapp-8e5db',
    storageBucket: 'chatapp-8e5db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAohrRb13iNLoT7l8WU51w2mH9PV8Owjv8',
    appId: '1:301675624288:ios:98d9f952eceea851025005',
    messagingSenderId: '301675624288',
    projectId: 'chatapp-8e5db',
    storageBucket: 'chatapp-8e5db.appspot.com',
    iosBundleId: 'com.example.chatAppProj',
  );
}
